### ISSUE TITLE
$SDRROOT is empty

### ISSUE THREAD

**Issue by jcsellers** [Axios-Engineering/openembedded-hawk#2]
When we installed this in the emulator, none of the provided components/devices etc were installed in the image.

**Comment by jcsellers** [comment]
figured this out. I created a new package group called packagegroup-redhawk-apps and just added the recipes I needed.  Can push later.

**Comment by bagoulla** [comment]
The recipes I've provided are below. Unless they are included in your image, or waveform, none of them will be installed by default. 
redhawk-AmFmPmBasebandDemod_2.0.0.bb redhawk-ArbitraryRateResampler_2.0.0.bb redhawk-fastfilter_2.0.0.bb redhawk-FrontEndController_1.0.0.bb redhawk-psksoft_2.0.0.bb redhawk-RBDSDecoder_2.0.1.bb redhawk-siggen_2.0.1.bb redhawk-TuneFilterDecimate_2.0.0.bb
