### ISSUE TITLE
cant bring up sandbox

### ISSUE THREAD

**Issue by jcsellers** [Axios-Engineering/openembedded-hawk#3]
Installed both package groups. Can get nodeBooter to bring up domain but cant bring up python to try to launch sandbox. included meta-oe/meta-python in build and still python doesnt come on.

**Comment by bagoulla** [comment]
By default the python libraries of redhawk have been put into their own recipes to keep file size down and eliminate the python runtime dependency. Including redhawk-core-python will bring it in, and redhawk-bulkio-python etc. It does look like there are still import errors though that I've lost going from dizzy to krogoth. Bringing in meta-openembedded/meta-python and leveraging their python-xml and python-lxml resolves the imports. See the latest README.md and the recent update.
